
/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: /Users/danel/KreMLin/krml BufferAlloc.fst
 * F* version: 43fbe5dc
 * KreMLin version: a3d914df
 */

#include "kremlib.h"
#ifndef __BufferAlloc_H
#define __BufferAlloc_H

#include "Prims.h"
#include "LowStar_Buffer.h"
#include "FStar.h"
#include "LowStar_Modifies.h"
#include "LowStar_ModifiesPat.h"
#include "LowStar_BufferOps.h"


uint64_t BufferAlloc_f();

#define __BufferAlloc_H_DEFINED
#endif
