include ../Makefile.include

all:
	$(FSTAR) Incr.fst
	$(FSTAR) Sum.fst
	$(FSTAR) Stack.fsti
	$(FSTAR) Stack.fst
	$(FSTAR) StackClient.fst
	$(FSTAR) RefinedStack.fsti
	$(FSTAR) SumST.fst
	$(FSTAR) InitFreezeMST.fst

clean:
	rm -dfr *~ *.exe out
