
/* This file was generated by KreMLin <https://github.com/FStarLang/kremlin>
 * KreMLin invocation: /Users/danel/KreMLin/krml BufferAlloc.fst
 * F* version: 43fbe5dc
 * KreMLin version: a3d914df
 */

#include "BufferAlloc.h"

uint64_t BufferAlloc_f()
{
  uint64_t b[64U] = { 0U };
  b[0U] = b[0U] + (uint64_t)32U;
  uint64_t r = b[0U];
  return r;
}

